[config]
skip_core_tasks = true

[tasks.default]
description = "Build and push docker image"
dependencies = ["docker-build", "docker-push"]

[tasks.docker-build]
command = "docker"
args = ["buildx", "build", "--platform=linux/amd64", "-t", "movingju/test:dasom_front", "."]

[tasks.docker-push]
command = "docker"
args = ["push", "movingju/test:dasom_front"]

